name: kawai
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  dio: ^5.1.2
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  uuid: ^3.0.7
  sqflite: ^2.2.8+4
  cupertino_icons: ^1.0.2
  flutter_cache_manager: ^3.3.0
  flutter_wallpaper_manager: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Huballi
      fonts:
        - asset: assets/fonts/Hubballi-Regular.ttf
    - family: Mplus
      fonts:
        - asset: assets/fonts/MPLUS1p-Regular.ttf