name: kawai
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  dio: ^5.1.2
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
